### ISSUE TITLE
Bullet for H3 headers not aligned

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#1]
The bullet for H3 header is not center-aligned with the text. Is this by design?

<img width="251" alt="CleanShot 2022-07-28 at 09 17 34" src="https://user-images.githubusercontent.com/28934641/181514889-f5469cc1-5135-4f9d-bd9f-d5e536b1c3b2.png">

**Comment by gavinmn** [comment]
Not by design, but I haven't found a workaround yet for adjusting this when the font size is made smaller.

**Comment by eryc-cc** [comment]
Here's a quick workaround that I found.

https://github.com/logseq/logseq/issues/4261#issuecomment-1198945742

> If you're looking for a quick fix, you can add the following code to your `custom.css`:
> 
> ```css
> :not(.block-ref) .ls-block h1,
> :not(.block-ref) .ls-block h2,
> :not(.block-ref) .ls-block h3,
> :not(.block-ref) .ls-block h4,
> :not(.block-ref) .ls-block h5,
> :not(.block-ref) .ls-block h6 {
> 	transform: translateY(-4px);
> }
> ```
> 
> The reason why I'm using `translateY(-4px)` is because the `div` that wraps both the bullet with the text aligns them in the `baseline`. For some reason, when you decrease the size of the headings, it doesn't align properly.
> 
> Maybe it's because they're setting a fixed height? I didn't debug it enough...
> 
> Here's the screenshot of a `<h3>` tag. I changed the `font-size` to `1.125rem`, here's what it looks like when I inspect:
> 
> ### Without `translateY`:
> <img alt="Screen Shot 2022-07-29 at 3 56 30 AM" width="142" src="https://user-images.githubusercontent.com/101464991/181701253-5b11dca6-b8b2-4256-8862-5274178fb452.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 58 48 AM" width="317" src="https://user-images.githubusercontent.com/101464991/181701658-ef60a39c-1138-4638-9110-ba5a21808268.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 57 17 AM" width="319" src="https://user-images.githubusercontent.com/101464991/181701383-e1aae287-4a96-49f4-9a51-832ed5d2077c.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 57 33 AM" width="335" src="https://user-images.githubusercontent.com/101464991/181701426-ab36a377-b20c-4402-a07d-c60f7c8bbc2a.png">
> 
> ### With `translateY`:
> <img alt="Screen Shot 2022-07-29 at 3 59 18 AM" width="146" src="https://user-images.githubusercontent.com/101464991/181701742-40b084c4-3801-46a3-a795-41a2f7e06408.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 47 25 AM" width="318" src="https://user-images.githubusercontent.com/101464991/181699850-fc336fe1-8391-4ebb-99d1-8259028c341f.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 47 39 AM" width="317" src="https://user-images.githubusercontent.com/101464991/181699881-e6662c88-5f5d-4fd2-a638-652db7169315.png">
> 
> <img alt="Screen Shot 2022-07-29 at 3 47 57 AM" width="340" src="https://user-images.githubusercontent.com/101464991/181699917-0ef97c94-dfe5-405a-97b4-7f6b18af89b2.png">
> 
> I like to have my headings a little bit smaller than the default option, here's the code for it (it's working quite nicely with the translate change):
> 
> ```css
> /* Content Headings */
> .editor-inner .h1.uniline-block, :not(.block-ref) .ls-block h1 { 
> 	font-size: 1.675rem; 
> }
> .editor-inner .h2.uniline-block, :not(.block-ref) .ls-block h2 { 
> 	font-size: 1.375rem; 
> }
> .editor-inner .h3.uniline-block, :not(.block-ref) .ls-block h3 { 
> 	font-size: 1.125rem; 
> }
> .editor-inner .h4.uniline-block, :not(.block-ref) .ls-block h4 { 
> 	font-size: 1rem; 
> }
> .editor-inner .h5.uniline-block, :not(.block-ref) .ls-block h5 { 
> 	font-size: .875rem; 
> }
> .editor-inner .h6.uniline-block, :not(.block-ref) .ls-block h6 { 
> 	font-size: .75rem; 
> }
> ```

**Comment by gavinmn** [comment]
> Here's a quick workaround that I found

Thanks! I'll get this added

**Comment by eryc-cc** [comment]
@gavinmn Mind if I create a PR? 👀

**Comment by gavinmn** [comment]
> @gavinmn Mind if I create a PR? 👀 

Sure! I'd appreciate it.
