### ISSUE TITLE
right sidebar

### ISSUE THREAD

**Issue by crendl** [gavinmn/logseq-luma#10]
hi,
when expanding the right sidebar, it takes up too much space imo.

![image](https://user-images.githubusercontent.com/15796851/181728888-c5c1d6b6-ad65-4d6a-b16a-654e39a556cd.png)

**Comment by gavinmn** [comment]
I don't think this is related to the theme as I didn't make any edits to the width of the sidebar. If you hover over the upper left corner of it you can grab a drag handle and shrink the width.

**Comment by crendl** [comment]
correct! i didn't find the handle initially! 
thanks

**Comment by gavinmn** [comment]
> correct! i didn't find the handle initially! thanks

I think there _may_ be a bug in the theme that is causing the handle to be super small that I'll look at.
