### ISSUE TITLE
Missing "Create new page icon" from sidebar

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#2]
The sidebar does not show the "create new page" icon and action at the bottom of the sidebar.

Env: macOS Monterey (12.4)

![CleanShot 2022-07-28 at 09 26 11](https://user-images.githubusercontent.com/28934641/181516676-56151d15-3409-4b3e-8a9b-3a5f7aa81b1e.png)

**Comment by gavinmn** [comment]
Again, purposefully removed. To make it visible before I add customization options, edit line `380` of `custom.css`

**Comment by martindufort** [comment]
Ok nice. I see where you are going. 
Will change my workflow to create a new page from the Search dialog.
