### ISSUE TITLE
Issues when using with Bullet Threading Plugin 

### ISSUE THREAD

**Issue by StirlingBaker** [gavinmn/logseq-luma#21]
Hey Gavin, 

It's Anthony Baker. I know you're not responsible for the Bullet Threading plugin, but you and I have chatted on Twitter earlier about it. I'm still seeing issues.

Am on Luma 0.2.1 (latest) and seeing that the threading tied to your bullets is off — I think you mentioned this might have to do with sizing/positioning you've adjusted? Are you seeing this too?

<img width="788" alt="cleanshot-2022-07-29-204727@2x" src="https://user-images.githubusercontent.com/3048209/181871272-e3783dab-5b6b-4075-8d9a-8cfe06afa41f.png">

**Comment by gavinmn** [comment]
I _think_ #22  will fix this. I could only intermittently reproduce this. If you refresh Logseq, does the issue go away?

**Comment by StirlingBaker** [comment]
@gavinmn No, but let me disable my custom.css and see if it's anything I've done.

**Comment by StirlingBaker** [comment]
@gavinmn And it's 100% repro for me.

**Comment by gavinmn** [comment]
Still can't consistently reproduce this. Are you at 100% zoom level and using the theme completely as is? No other plugins enabled?

**Comment by gavinmn** [comment]
I can reproduce this now by disabling and enabling the plugin, but a refresh of Logseq fixes it every time. My thought is that Logseq is having trouble deciding which CSS to use — the bullet threading plugin's or my overrides to it, but I'm not sure how to verify that or fix it.

**Comment by StirlingBaker** [comment]
@gavinmn When you say "refresh" what do you specifically mean? A reload? Forced reload?

And yeah, one of the things that irks me about their custom.css is that it sometimes has issues where it seems like they're not honoring it fully or there's been a hiccup.

**Comment by StirlingBaker** [comment]
@gavinmn Okay, maybe it's just me. I have done the following, and in all cases, I still see the issue afterward.

1. Reload Logseq
2. Force reload Logseq
3. Disable and re-enable Bullet Threading
4. Uninstall and re-install Bullet Threading
5. Delete my custom.css

No idea what's going on, but in all the above cases (which were done independently of one another), the issue remained. Agh. I wish I didn't care. LOL.

**Comment by StirlingBaker** [comment]
@gavinmn Maybe I need to add am `!important` on your CSS attributes.

**Comment by gavinmn** [comment]
> When you say "refresh" what do you specifically mean? A reload? Forced reload?

`⌘+r` or `documents -> refresh`

@StirlingBaker can you try nothing in `custom.css` and just using the theme from the marketplace?

**Comment by StirlingBaker** [comment]
@gavinmn Did it. Here's what I see: 
<img width="813" alt="cleanshot-2022-07-31-080708@2x" src="https://user-images.githubusercontent.com/3048209/182032767-1db3b54f-9818-4a49-a463-659aa88aaa93.png">

This was after me deleting all copy from my custom.css and saving it, then refreshing Logseq from the Documents option menu.

**Comment by gavinmn** [comment]
Ok this time I think I was able to fix it. Could you update to the latest and tell me if it's working for you now?

**Comment by StirlingBaker** [comment]
@gavinmn Huzzah! It worked! Thanks a ton. 😁

![cleanshot-2022-07-31-111658](https://user-images.githubusercontent.com/3048209/182039882-f27575fd-37e8-44a7-a5b6-4dd3e14821e8.png)
