### ISSUE TITLE
Spacing in both Favorites and Recents sections is not consistent

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#23]
The spacing between elements in the Favorites and the Recents sections is not consistent. 
Same applies to the divider bar. 

<img width="90" alt="CleanShot 2022-07-30 at 09 33 50" src="https://user-images.githubusercontent.com/28934641/181916779-69202933-5955-4497-9357-6e29e069db8a.png">

**Comment by gavinmn** [comment]
Will be fixed in the next release
