### ISSUE TITLE
Sidebar missing "Favorite" and "Recent" headings

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#3]
The sidebar is not displaying the "Favorites" headings. The "Recent" section is empty.

Env: macOS Monterey 12.4
LogSeq: Version 0.7.8 (0.7.8)

![CleanShot 2022-07-28 at 09 26 11](https://user-images.githubusercontent.com/28934641/181517625-f61e0969-5bd3-4a28-a7cf-757062c450a1.png)

**Comment by gavinmn** [comment]
These are purposefully removed for a minimal look. In the future I'd like to add customization options, but for now if you'd like them back you can copy `custom.css` into `logseq/custom.css` and edit lines `166` and `368`.
