### ISSUE TITLE
Strike through poor contrast in dark mode

### ISSUE THREAD

**Issue by cemetary** [gavinmn/logseq-luma#31]
<img width="319" alt="Captura de Pantalla 2022-08-03 a la(s) 18 34 02" src="https://user-images.githubusercontent.com/10538213/182738741-d3fd9f52-ba72-4dbe-8b97-6b971be1d0c2.png">

Info
Luma versión: 0.2.4
Logseq version: 0.7.9
OS: macOS 12.5

**Comment by gavinmn** [comment]
Are you referring to the strike through?

**Comment by cemetary** [comment]
Yeah. Sorry, my English sucks.

**Comment by gavinmn** [comment]
No problem. I'll get this fixed for the next release
