### ISSUE TITLE
Feature request: add support for "Banners" and "Block calendar" plugins

### ISSUE THREAD

**Issue by yoyurec** [gavinmn/logseq-luma#34]
To do this main text color & bg color should be in HEX, not HSL.
https://github.com/gavinmn/logseq-luma/blob/main/custom.css#L43-L44

**Comment by gavinmn** [comment]
Could you elaborate?

**Comment by yoyurec** [comment]
first will try to do it on my side - convert ANY color space (including with alpha chanel) to RGB - there are few ideas...
