### ISSUE TITLE
Extensions icon is missing

### ISSUE THREAD

**Issue by cemetary** [gavinmn/logseq-luma#38]
Extensions icon is missing in Light and Dark Mode.

https://user-images.githubusercontent.com/10538213/183124536-de760553-37fc-4b13-860c-0b4cea097ba9.mov

**Comment by gavinmn** [comment]
This is intentional as I don't like the icon and haven't worked on getting a better one in there.

**Comment by frankjwu** [comment]
@cemetary i was playing around with this myself. in case you really want this icon back, you can drop this in your custom.css:

`.ls-icon-puzzle {
  display: block;
}`
