### ISSUE TITLE
increase space between linked references

### ISSUE THREAD

**Issue by reify-jorge-david-fernandez** [gavinmn/logseq-luma#40]
Linked references are rendered together without any whitespace in between
![CleanShot 2022-08-10 at 12 39 48](https://user-images.githubusercontent.com/100608106/183965780-65d408ea-c93d-4909-ad22-45a67e95d68e.png)

**Comment by gavinmn** [comment]
I think this was a bug introduced in Logseq 0.80. I'll be working on a release that will address all the 0.80 fixes soon.

**Comment by gavinmn** [comment]
Fixed with 517cf50
