### ISSUE TITLE
dropdown list is not displayed in its entirety

### ISSUE THREAD

**Issue by integratorivan** [gavinmn/logseq-luma#42]
if i open dropdown when i switch folder, my dropdown not displayed.
but i swith to default theme -- all good
<img width="2205" alt="Снимок экрана 2022-10-03 в 20 11 06" src="https://user-images.githubusercontent.com/40823204/193637724-34ade934-ea1a-40fd-87a9-5f8310f3eb26.png">
<img width="2205" alt="Снимок экрана 2022-10-03 в 20 11 23" src="https://user-images.githubusercontent.com/40823204/193637778-2a0b63bd-61fb-49f2-a272-e802c714af80.png">

**Comment by gavinmn** [comment]
Looks like I've got a `z-index` issue going on. I'll try and get this fixed for the next release

**Comment by integratorivan** [comment]
yep, i fix this changed `main-content-container: z-index: 9` to `z-index-8`. But i dont know why `dropdown-wrapper` with `z-index: 1000 !important` cant work)

**Comment by gavinmn** [comment]
@ivanvkt feel free to open a PR in the future for changes like these!

**Comment by integratorivan** [comment]
@gavinmn cool!!! next time I'll open it, didn't think of that))
