### ISSUE TITLE
Favorites list not aligned

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#43]
![CleanShot 2022-10-06 at 15 38 07](https://user-images.githubusercontent.com/28934641/194403693-a21745c1-81b0-40dc-b28f-2dd1deba7b0c.png)

---
macOS 12.5.1
LogSeq 0.8.8
Luma 0.2.10

**Comment by subnut** [comment]
@martindufort Please check if #45 solves this issue for you
