### ISSUE TITLE
Please make hiding top bar optional

### ISSUE THREAD

**Issue by hphoeksma** [gavinmn/logseq-luma#46]
I love your theme! Please make the hiding top bar configurable - I really would love to disable this ;-)

**Comment by ituri** [comment]
+1 😊

**Comment by gavinmn** [comment]
I want to do this but I likely won't be adding settings to the theme for a while. Feel free to comment out lines 937-953 in the CSS in the meantime 

https://github.com/gavinmn/logseq-luma/blob/e0ec83f41be467aea334781d48e1173008b587f3/custom.css#LL937-L953C2

**Comment by hphoeksma** [comment]
@gavinmn no problem. I forked your repo and commented this out. If anyone want this disabled they can use this line in their custom css:

`@import url('https://hphoeksma.github.io/logseq-luma/custom.css');`
