### ISSUE TITLE
no access top nav buttons

### ISSUE THREAD

**Issue by jenningsb2** [gavinmn/logseq-luma#5]
Hey! It appears as though the top nav buttons are gone. 

I'd like to at least have access to the sidebar buttons (the keyboard shortcuts work fine for now) 

![CleanShot 2022-07-28 at 17 10 32@2x](https://user-images.githubusercontent.com/29644050/181638245-fed44d14-f95a-498c-a4f2-8f08c2ad0b18.png)

**Comment by jenningsb2** [comment]
If this is intentional, I can add them back via custom CSS

**Comment by gavinmn** [comment]
v0.1.3 adds these back by default
