### ISSUE TITLE
Header in mobile shifted up

### ISSUE THREAD

**Issue by jorda0mega** [gavinmn/logseq-luma#8]
![5A761C49-35DF-4AA0-AEA7-9FA464B1AFF4](https://user-images.githubusercontent.com/484084/181679079-35ee27fa-0a38-46b5-bb2f-14e7fe78e4d9.jpeg)

**Comment by gavinmn** [comment]
Hmm, I'm unable to reproduce this. What device, version OS, and Logseq version are you running?

**Comment by martindufort** [comment]
Getting same behavior on my iPhone.  
Makes Home, "hamburger" menu and the (...) menu unresponsive. 

Env: 
- iPhone XR
- iOS 15.5
- LogSeq: 0.7.7
- 
![IMG_DC9F33248EAD-1](https://user-images.githubusercontent.com/28934641/181758571-8416fd75-38d5-4b6c-a47c-4f6ea4201422.jpeg)

**Comment by gavinmn** [comment]
Could you test out removing lines 231 – 233 of `custom.css`? This part: 

```
 .cp__header {
    height: 44px;
  }
```
That may be causing the issue. I'm running iOS 16 and can't reproduce it which might be contributing too.

**Comment by gavinmn** [comment]
On second thought, something seems to be wrong with the media query to detect mobile — you should not be seeing the card background on mobile but rather a full viewport layout. I'll have to take a deeper look.
